"""Local model loading and chat service package."""

from .backend import BackendProcess, LlmBackend, MlxLmBackend
from .service import LlmService
from .routes import Route, RouteResult, build_routes, encode_sse

from .state import (
    DEFAULT_LLM_PORT,
    ERR_BACKEND_EXITED,
    ERR_EVICTED,
    ERR_LOAD_IN_PROGRESS,
    ERR_LOAD_TIMEOUT,
    ERR_MEDIA_BUSY,
    ERR_MODEL_DIR_MISSING,
    ERR_MODEL_MISMATCH,
    ERR_MODEL_NOT_FOUND,
    ERR_NO_MODEL_LOADED,
    ERR_PORT_NOT_RELEASED,
    ERR_UPSTREAM_ERROR,
    STATUS_ERROR,
    STATUS_IDLE,
    STATUS_LOADED,
    STATUS_LOADING,
    LlmError,
    LlmRejected,
    LlmState,
    LoadedModel,
    UpstreamError,
    delta_event,
    done_event,
    error_event,
)

__all__ = [
    "BackendProcess",
    "DEFAULT_LLM_PORT",
    "ERR_BACKEND_EXITED",
    "ERR_EVICTED",
    "ERR_LOAD_IN_PROGRESS",
    "ERR_LOAD_TIMEOUT",
    "ERR_MEDIA_BUSY",
    "ERR_MODEL_DIR_MISSING",
    "ERR_MODEL_MISMATCH",
    "ERR_MODEL_NOT_FOUND",
    "ERR_NO_MODEL_LOADED",
    "ERR_PORT_NOT_RELEASED",
    "ERR_UPSTREAM_ERROR",
    "STATUS_ERROR",
    "STATUS_IDLE",
    "STATUS_LOADED",
    "STATUS_LOADING",
    "LlmError",
    "LlmService",
    "Route",
    "RouteResult",
    "LlmBackend",
    "LlmRejected",
    "LlmState",
    "LoadedModel",
    "MlxLmBackend",
    "UpstreamError",
    "delta_event",
    "done_event",
    "error_event",
    "build_routes",
    "encode_sse",
]
